### ISSUE TITLE
question about confidentiality

### ISSUE THREAD

**Issue by mauddelagarde** [A-BN/ClermonTyping#10]
Hello,

I would like to use the Clermont typing interface, but I could not find any informations on the confidentiality of my data. Does the downloaded sequence stay confidential?

Thank you for your time.
Maud

**Comment by A-BN** [comment]
Dear Maude de Lagarde,

The data are erased every 24:00 and stay absolutely confidential.
I hope to see your research using the clermontyping published soon!
Antoine Bridier-Nahmias

**Comment by mauddelagarde** [comment]
Thank you for that quick answer!
________________________________
De : A-BN [notifications@github.com]
Envoyé : mercredi 17 octobre 2018 09:16
À : A-BN/ClermonTyping
Cc : de Lagarde Maud; Author
Objet : Re: [A-BN/ClermonTyping] question about confidentiality (#10)


Dear Maude de Lagarde,

The data are erased every 24:00 and stay absolutely confidential.
I hope to see your research using the clermontyping published soon!
Antoine Bridier-Nahmias
