### ISSUE TITLE
Problems with mash group determination

### ISSUE THREAD

**Issue by mdtorohernando** [A-BN/ClermonTyping#22]
Dear developer, I am getting problems when analyzing Clermont scheme when comparing CLI vs Web tool. When using CLI mode, mash_group does not appear. I send to you both screen captures. 

Thanks!
![ClermonTyping_CLI](https://user-images.githubusercontent.com/26143966/60710184-638e2b00-9f12-11e9-95b5-82ed69f8f92a.png)
![ClermonTyping_web](https://user-images.githubusercontent.com/26143966/60710187-6557ee80-9f12-11e9-9176-e576f236187d.png)

**Comment by A-BN** [comment]
Dear mdtorohernando,
I think this problem was only present in a very short lived commit (the mash binary was simply absent from the repo!), you might have cloned the repo then, before we catch the mistake. It has been corrected now in commit d2d1e1dfa2f85c913fcd9961850f0e82e6c6f0d8 .
Is it working now?

**Comment by mdtorohernando** [comment]
Hi! thanks for your quick answer. I just downloaded the zip master file from the repository this morning. I'm going to check again

**Comment by mdtorohernando** [comment]
This time I downloaded as 'git clone https://github.com/A-BN/ClermonTyping.git' (instead of downloading the master .zip file) and the result is the same
![image](https://user-images.githubusercontent.com/26143966/60711592-8e2db300-9f15-11e9-9395-b8958b28258a.png)

**Comment by A-BN** [comment]
`mash` binary wasn't flagged as executable!
It should be working now.
Thank you for your input.

**Comment by mdtorohernando** [comment]
thanks!!! I made executable mash from the bin file and now it works really fine! thank you!
