### ISSUE TITLE
Error 'files doesn't exists'

### ISSUE THREAD

**Issue by jpaganini** [A-BN/ClermonTyping#31]
Hi people,

How are you? I hope you are doing fine! Thanks a lot for this wonderful tool, I've been using it a lot in my research!

I just wanted to report an issue that I'm getting when running the latest version of clermonTyping with multiple files simulatneously. As indicated by the manual, I'm running the command:

`../clermonTyping.sh --fasta file1.fna@file2.fna@file3.fna --name clermon_output`

However, when I do this, I'm getting an error that states:

`file1.fna file2.fna file3.fna does not exitst.`

I've tried to run this with relative and absolute paths to the fasta files, but I always get the same error. 

I run the tool with a previous verison of the script clermonTyping.sh (version 1.4.1) and it works perfect. 

I hope this helps! Let me know if you required any additional information on my side.
Have a wonderful day!

Cheers,

**Comment by A-BN** [comment]
@Benedicte-C spotted the problem and patched it you can update your version of ClermonTyping right away!
Thanks for your precise description of the problem.
Antoine.
